'use strict';

// Web Tools (개발자 도구)
var webTools = [
  { id: 'password-generator', title: { ko: '비밀번호 생성기', en: 'Password Generator', ja: 'パスワード生成' }, emoji: '🔐', desc: { ko: '안전한 비밀번호 생성', en: 'Generate secure passwords', ja: '安全なパスワード生成' } },
  { id: 'qr-generator', title: { ko: 'QR 코드 생성', en: 'QR Code Generator', ja: 'QRコード生成' }, emoji: '📱', desc: { ko: 'QR 코드 빠르게 생성', en: 'Generate QR codes', ja: 'QRコード生成' } },
  { id: 'json-formatter', title: { ko: 'JSON 포매터', en: 'JSON Formatter', ja: 'JSONフォーマッター' }, emoji: '📋', desc: { ko: 'JSON 정리 및 검증', en: 'Format and validate JSON', ja: 'JSON整形と検証' } },
  { id: 'uuid-generator', title: { ko: 'UUID 생성기', en: 'UUID Generator', ja: 'UUID生成' }, emoji: '🆔', desc: { ko: 'UUID v1/v4 생성', en: 'Generate UUID v1/v4', ja: 'UUID v1/v4生成' } },
  { id: 'base64-tool', title: { ko: 'Base64 인코더', en: 'Base64 Encoder', ja: 'Base64エンコーダー' }, emoji: '🔤', desc: { ko: 'Base64 인코딩/디코딩', en: 'Base64 encode/decode', ja: 'Base64エンコード/デコード' } },
  { id: 'color-converter', title: { ko: '색상 변환기', en: 'Color Converter', ja: 'カラーコンバーター' }, emoji: '🎨', desc: { ko: 'HEX/RGB/HSL 변환', en: 'HEX/RGB/HSL converter', ja: 'HEX/RGB/HSL変換' } },
  { id: 'hash-generator', title: { ko: '해시 생성기', en: 'Hash Generator', ja: 'ハッシュ生成' }, emoji: '🔒', desc: { ko: 'MD5/SHA 해시 생성', en: 'Generate MD5/SHA hash', ja: 'MD5/SHAハッシュ生成' } },
  { id: 'word-counter', title: { ko: '단어 수 세기', en: 'Word Counter', ja: '単語カウンター' }, emoji: '📊', desc: { ko: '단어/글자 수 계산', en: 'Count words and characters', ja: '単語/文字数カウント' } },
  { id: 'url-encoder', title: { ko: 'URL 인코더', en: 'URL Encoder', ja: 'URLエンコーダー' }, emoji: '🔗', desc: { ko: 'URL 인코딩/디코딩', en: 'URL encode/decode', ja: 'URLエンコード/デコード' } },
  { id: 'timestamp-converter', title: { ko: '타임스탬프 변환', en: 'Timestamp Converter', ja: 'タイムスタンプ変換' }, emoji: '⏰', desc: { ko: 'Unix 타임스탬프 변환', en: 'Unix timestamp converter', ja: 'Unixタイムスタンプ変換' } },
  { id: 'regex-tester', title: { ko: '정규식 테스터', en: 'Regex Tester', ja: '正規表現テスター' }, emoji: '🔍', desc: { ko: '정규표현식 실시간 테스트', en: 'Test regex patterns', ja: '正規表現テスト' } },
  { id: 'jwt-decoder', title: { ko: 'JWT 디코더', en: 'JWT Decoder', ja: 'JWTデコーダー' }, emoji: '🎫', desc: { ko: 'JWT 토큰 파싱', en: 'Parse JWT tokens', ja: 'JWTトークン解析' } },
  { id: 'lorem-ipsum', title: { ko: '로렘 입숨', en: 'Lorem Ipsum', ja: 'Lorem Ipsum' }, emoji: '📝', desc: { ko: '더미 텍스트 생성', en: 'Generate dummy text', ja: 'ダミーテキスト生成' } },
  { id: 'json-to-typescript', title: { ko: 'JSON→TypeScript', en: 'JSON→TypeScript', ja: 'JSON→TypeScript' }, emoji: '⚡', desc: { ko: 'JSON을 TS 타입으로 변환', en: 'Convert JSON to TS types', ja: 'JSONをTS型に変換' } },
  { id: 'css-minifier', title: { ko: 'CSS 압축기', en: 'CSS Minifier', ja: 'CSS圧縮' }, emoji: '💨', desc: { ko: 'CSS 파일 압축', en: 'Minify CSS files', ja: 'CSSファイル圧縮' } },
  { id: 'html-minifier', title: { ko: 'HTML 압축기', en: 'HTML Minifier', ja: 'HTML圧縮' }, emoji: '🗜️', desc: { ko: 'HTML 파일 압축', en: 'Minify HTML files', ja: 'HTMLファイル圧縮' } },
  { id: 'sql-formatter', title: { ko: 'SQL 포매터', en: 'SQL Formatter', ja: 'SQLフォーマッター' }, emoji: '🗄️', desc: { ko: 'SQL 쿼리 정리', en: 'Format SQL queries', ja: 'SQLクエリ整形' } },
  { id: 'markdown-to-html', title: { ko: '마크다운→HTML', en: 'Markdown→HTML', ja: 'Markdown→HTML' }, emoji: '📄', desc: { ko: '마크다운을 HTML로 변환', en: 'Convert Markdown to HTML', ja: 'MarkdownをHTMLに変換' } },
  { id: 'image-to-base64', title: { ko: '이미지→Base64', en: 'Image→Base64', ja: '画像→Base64' }, emoji: '🖼️', desc: { ko: '이미지를 Base64로 변환', en: 'Convert images to Base64', ja: '画像をBase64に変換' } },
  { id: 'name-generator', title: { ko: '랜덤 이름 생성', en: 'Random Name Generator', ja: 'ランダム名前生成' }, emoji: '👤', desc: { ko: '랜덤 이름 생성', en: 'Generate random names', ja: 'ランダム名前生成' } },
  { id: 'color-palette', title: { ko: '컬러 팔레트', en: 'Color Palette', ja: 'カラーパレット' }, emoji: '🎨', desc: { ko: '컬러 팔레트 생성', en: 'Generate color palettes', ja: 'カラーパレット生成' } },
  { id: 'cron-generator', title: { ko: 'Cron 생성기', en: 'Cron Generator', ja: 'Cron生成' }, emoji: '⏱️', desc: { ko: 'Cron 표현식 생성', en: 'Generate cron expressions', ja: 'Cron式生成' } },
  { id: 'diff-checker', title: { ko: '텍스트 비교', en: 'Diff Checker', ja: 'テキスト比較' }, emoji: '🔄', desc: { ko: '텍스트 차이 비교', en: 'Compare text differences', ja: 'テキスト差分比較' } },
  { id: 'pomodoro-timer', title: { ko: '뽀모도로 타이머', en: 'Pomodoro Timer', ja: 'ポモドーロタイマー' }, emoji: '🍅', desc: { ko: '집중 타이머', en: 'Focus timer', ja: '集中タイマー' } },
  { id: 'slug-generator', title: { ko: 'URL 슬러그', en: 'Slug Generator', ja: 'スラッグ生成' }, emoji: '🔗', desc: { ko: 'URL 슬러그 생성', en: 'Generate URL slugs', ja: 'URLスラッグ生成' } },
  { id: 'ip-info', title: { ko: 'IP 정보', en: 'IP Info', ja: 'IP情報' }, emoji: '🌐', desc: { ko: 'IP 주소 정보 조회', en: 'Lookup IP address info', ja: 'IPアドレス情報' } },
  { id: 'css-gradient', title: { ko: 'CSS 그라디언트', en: 'CSS Gradient', ja: 'CSSグラデーション' }, emoji: '🌈', desc: { ko: 'CSS 그라디언트 생성', en: 'Generate CSS gradients', ja: 'CSSグラデーション生成' } },
  { id: 'box-shadow', title: { ko: 'Box Shadow', en: 'Box Shadow', ja: 'ボックスシャドウ' }, emoji: '📦', desc: { ko: 'CSS 박스 쉐도우 생성', en: 'Generate CSS box shadow', ja: 'CSSボックスシャドウ生成' } },
  { id: 'emoji-picker', title: { ko: '이모지 선택', en: 'Emoji Picker', ja: '絵文字ピッカー' }, emoji: '😀', desc: { ko: '이모지 검색 및 복사', en: 'Search and copy emoji', ja: '絵文字検索とコピー' } },
  { id: 'text-case-converter', title: { ko: '텍스트 변환', en: 'Text Case Converter', ja: 'テキストケース変換' }, emoji: '🔡', desc: { ko: '대소문자 변환', en: 'Convert text case', ja: '大文字小文字変換' } },
  { id: 'aspect-ratio', title: { ko: '비율 계산기', en: 'Aspect Ratio', ja: 'アスペクト比' }, emoji: '📐', desc: { ko: '이미지 비율 계산', en: 'Calculate aspect ratio', ja: 'アスペクト比計算' } },
  { id: 'binary-hex', title: { ko: '진법 변환', en: 'Binary/Hex Converter', ja: '進数変換' }, emoji: '🔢', desc: { ko: '2/10/16진수 변환', en: 'Binary/Decimal/Hex converter', ja: '2/10/16進数変換' } },
  { id: 'meta-tag-generator', title: { ko: '메타 태그 생성', en: 'Meta Tag Generator', ja: 'メタタグ生成' }, emoji: '🏷️', desc: { ko: 'SEO 메타 태그 생성', en: 'Generate SEO meta tags', ja: 'SEOメタタグ生成' } }
];

// Consumer Tools (일반 사용자 도구)
var consumerTools = [
  { id: 'daily-fortune', title: { ko: '오늘의 운세', en: 'Daily Fortune', ja: '今日の運勢' }, emoji: '🔮', desc: { ko: '별자리/띠/혈액형 운세', en: 'Zodiac & horoscope fortune', ja: '星座/干支/血液型占い' } },
  { id: 'mbti-test', title: { ko: 'MBTI 테스트', en: 'MBTI Test', ja: 'MBTIテスト' }, emoji: '🧩', desc: { ko: '16가지 성격 유형 테스트', en: '16 personality types test', ja: '16性格タイプテスト' } },
  { id: 'dream-interpreter', title: { ko: '꿈 해몽', en: 'Dream Interpreter', ja: '夢占い' }, emoji: '💭', desc: { ko: 'AI 꿈 해석', en: 'AI dream interpretation', ja: 'AI夢診断と解釈' } },
  { id: 'compatibility-test', title: { ko: '궁합 테스트', en: 'Compatibility Test', ja: '相性診断' }, emoji: '💕', desc: { ko: '이름/생년월일 궁합', en: 'Name & birthday compatibility', ja: '名前/誕生日相性' } },
  { id: 'ai-tarot', title: { ko: 'AI 타로', en: 'AI Tarot', ja: 'AIタロット' }, emoji: '🃏', desc: { ko: '타로 카드 점', en: 'AI tarot card reading', ja: 'AIタロットカード占い' } },
  { id: 'char-counter', title: { ko: '글자수 세기', en: 'Character Counter', ja: '文字数カウント' }, emoji: '📏', desc: { ko: '글자 수 계산기', en: 'Count characters', ja: '文字数カウンター' } },
  { id: 'bmi-calculator', title: { ko: 'BMI 계산기', en: 'BMI Calculator', ja: 'BMI計算機' }, emoji: '⚖️', desc: { ko: '체질량 지수 계산', en: 'Calculate BMI', ja: 'BMI計算' } },
  { id: 'dday-calculator', title: { ko: 'D-Day 계산기', en: 'D-Day Calculator', ja: 'Dデイ計算機' }, emoji: '📅', desc: { ko: '디데이 계산', en: 'Calculate D-Day', ja: 'Dデイ計算' } },
  { id: 'age-calculator', title: { ko: '나이 계산기', en: 'Age Calculator', ja: '年齢計算機' }, emoji: '🎂', desc: { ko: '정확한 나이 계산', en: 'Calculate exact age', ja: '正確な年齢計算' } },
  { id: 'percent-calculator', title: { ko: '퍼센트 계산기', en: 'Percent Calculator', ja: 'パーセント計算機' }, emoji: '💯', desc: { ko: '퍼센트 계산', en: 'Calculate percentages', ja: 'パーセント計算' } },
  { id: 'unit-converter', title: { ko: '단위 변환기', en: 'Unit Converter', ja: '単位変換' }, emoji: '🔄', desc: { ko: '길이/무게/온도 변환', en: 'Convert units', ja: '長さ/重さ/温度変換' } },
  { id: 'gpa-calculator', title: { ko: '학점 계산기', en: 'GPA Calculator', ja: '成績計算機' }, emoji: '📚', desc: { ko: '학점 평균 계산', en: 'Calculate GPA', ja: '成績平均計算' } },
  { id: 'message-generator', title: { ko: '메시지 생성기', en: 'Message Generator', ja: 'メッセージ生成' }, emoji: '✉️', desc: { ko: '축하/감사 메시지 생성', en: 'Generate messages', ja: 'お祝い/感謝メッセージ生成' } },
  { id: 'insta-caption', title: { ko: '인스타 캡션', en: 'Insta Caption', ja: 'インスタキャプション' }, emoji: '📸', desc: { ko: '인스타그램 캡션 생성', en: 'Generate Instagram captions', ja: 'Instagramキャプション生成' } },
  { id: 'saju-fortune', title: { ko: '사주 풀이', en: 'Saju Fortune', ja: '四柱推命' }, emoji: '📿', desc: { ko: '사주팔자 분석', en: 'Four pillars reading', ja: '四柱推命分析' } },
  { id: 'palm-reading', title: { ko: '손금 보기', en: 'Palm Reading', ja: '手相占い' }, emoji: '✋', desc: { ko: 'AI 손금 분석', en: 'AI palm reading', ja: 'AI手相占い' } },
  { id: 'lotto-fortune', title: { ko: '로또 번호', en: 'Lotto Numbers', ja: 'ロト番号' }, emoji: '🎰', desc: { ko: '행운의 로또 번호 생성', en: 'Generate lucky lotto numbers', ja: '幸運のロト番号生成' } },
  { id: 'biorhythm', title: { ko: '바이오리듬', en: 'Biorhythm', ja: 'バイオリズム' }, emoji: '📈', desc: { ko: '신체/감성/지성 리듬', en: 'Physical/Emotional/Intellectual rhythm', ja: '身体/感情/知性リズム' } },
  { id: 'past-life', title: { ko: '전생 테스트', en: 'Past Life Test', ja: '前世テスト' }, emoji: '🌟', desc: { ko: '전생 직업 및 시대', en: 'Past life era & occupation', ja: '前世職業と時代' } },
  { id: 'spirit-animal', title: { ko: '동물 성격 테스트', en: 'Spirit Animal Test', ja: '動物性格テスト' }, emoji: '🦁', desc: { ko: '나의 동물 성격 찾기', en: 'Find your spirit animal', ja: '自分の動物性格を探す' } },
  { id: 'face-reading', title: { ko: '관상 분석', en: 'Face Reading', ja: '人相占い' }, emoji: '👤', desc: { ko: 'AI 관상 운세', en: 'AI face reading fortune', ja: 'AI人相占い' } },
  { id: 'love-style', title: { ko: '연애 성향 테스트', en: 'Love Style Test', ja: '恋愛スタイルテスト' }, emoji: '💖', desc: { ko: '나의 연애 유형 찾기', en: 'Find your love style', ja: '自分の恋愛タイプを探す' } },
  { id: 'past-life-couple', title: { ko: '전생의 인연', en: 'Past Life Couple', ja: '前世の縁' }, emoji: '💫', desc: { ko: '커플 전생 관계', en: 'Past life couple relationship', ja: 'カップル前世関係' } },
  { id: 'new-year-2025', title: { ko: '2025 한마디', en: '2025 Message', ja: '2025メッセージ' }, emoji: '🎊', desc: { ko: '새해 운세 메시지', en: 'New year fortune message', ja: '新年運勢メッセージ' } },
  { id: 'random-picker', title: { ko: '랜덤 뽑기', en: 'Random Picker', ja: 'ランダムピッカー' }, emoji: '🎲', desc: { ko: '랜덤 선택 도구', en: 'Random selection tool', ja: 'ランダム選択ツール' } },
  { id: 'name-generator', title: { ko: 'AI 이름 생성기', en: 'AI Name Generator', ja: 'AIネーミングツール' }, emoji: '🪄', desc: { ko: '아기/펫/브랜드 이름 생성', en: 'Generate baby, pet, and brand names', ja: '赤ちゃん・ペット・ブランド名を生成' } },
  { id: 'ladder-game', title: { ko: '사다리 게임', en: 'Ladder Game', ja: 'はしごゲーム' }, emoji: '🪜', desc: { ko: '온라인 사다리 타기', en: 'Online ladder game', ja: 'オンラインはしごゲーム' } },
  { id: 'number-to-korean', title: { ko: '숫자 한글 변환', en: 'Number to Korean', ja: '数字韓国語変換' }, emoji: '🔢', desc: { ko: '숫자를 한글로 변환', en: 'Convert numbers to Korean', ja: '数字を韓国語に変換' } },
  { id: 'coin-flip', title: { ko: '동전 던지기', en: 'Coin Flip', ja: 'コイン投げ' }, emoji: '🪙', desc: { ko: '온라인 동전 던지기', en: 'Online coin flip', ja: 'オンラインコイン投げ' } },
  { id: 'random-number', title: { ko: '랜덤 숫자', en: 'Random Number', ja: 'ランダム数字' }, emoji: '🎲', desc: { ko: '무작위 숫자 생성', en: 'Generate random numbers', ja: 'ランダム数字生成' } },
  { id: 'text-repeater', title: { ko: '텍스트 반복', en: 'Text Repeater', ja: 'テキスト繰り返し' }, emoji: '🔄', desc: { ko: '텍스트 반복 생성', en: 'Repeat text multiple times', ja: 'テキストを繰り返す' } },
  { id: 'stopwatch', title: { ko: '스톱워치', en: 'Stopwatch', ja: 'ストップウォッチ' }, emoji: '⏱️', desc: { ko: '온라인 초시계', en: 'Online stopwatch', ja: 'オンラインストップウォッチ' } },
  { id: 'dice-roller', title: { ko: '주사위 굴리기', en: 'Dice Roller', ja: 'サイコロ' }, emoji: '🎲', desc: { ko: '온라인 주사위', en: 'Online dice roller', ja: 'オンラインサイコロ' } },
  { id: 'timer', title: { ko: '타이머', en: 'Timer', ja: 'タイマー' }, emoji: '⏲️', desc: { ko: '카운트다운 타이머', en: 'Countdown timer', ja: 'カウントダウンタイマー' } },
  { id: 'metronome', title: { ko: '메트로놈', en: 'Metronome', ja: 'メトロノーム' }, emoji: '🎵', desc: { ko: '온라인 메트로놈', en: 'Online metronome', ja: 'オンラインメトロノーム' } },
  { id: 'fullscreen-clock', title: { ko: '전체화면 시계', en: 'Fullscreen Clock', ja: 'フルスクリーン時計' }, emoji: '🕐', desc: { ko: '큰 디지털 시계', en: 'Large digital clock', ja: '大きなデジタル時計' } },
  { id: 'screen-ruler', title: { ko: '화면 눈금자', en: 'Screen Ruler', ja: 'スクリーンルーラー' }, emoji: '📏', desc: { ko: '픽셀 측정 도구', en: 'Pixel measurement tool', ja: 'ピクセル測定ツール' } },
  { id: 'breathing-exercise', title: { ko: '호흡 운동', en: 'Breathing Exercise', ja: '呼吸エクササイズ' }, emoji: '🧘', desc: { ko: '스트레스 해소 호흡법', en: 'Stress relief breathing', ja: 'ストレス解消呼吸法' } },
  { id: 'white-noise', title: { ko: '백색 소음', en: 'White Noise', ja: 'ホワイトノイズ' }, emoji: '🎧', desc: { ko: '집중력 향상 사운드', en: 'Focus enhancement sounds', ja: '集中力向上サウンド' } },
  { id: 'color-picker', title: { ko: '색상 선택기', en: 'Color Picker', ja: 'カラーピッカー' }, emoji: '🎨', desc: { ko: 'HEX/RGB/HSL 색상 선택', en: 'HEX/RGB/HSL color picker', ja: 'HEX/RGB/HSLカラー選択' } },
  { id: 'notepad', title: { ko: '온라인 메모장', en: 'Online Notepad', ja: 'オンラインメモ帳' }, emoji: '📝', desc: { ko: '브라우저 메모장', en: 'Browser notepad', ja: 'ブラウザメモ帳' } },
  { id: 'flip-clock', title: { ko: '플립 시계', en: 'Flip Clock', ja: 'フリップ時計' }, emoji: '🕐', desc: { ko: '복고풍 디지털 시계', en: 'Retro digital clock', ja: 'レトロデジタル時計' } },
  { id: 'pomodoro-focus', title: { ko: '뽀모도로 집중', en: 'Pomodoro Focus', ja: 'ポモドーロ集中' }, emoji: '🍅', desc: { ko: '집중력 향상 타이머', en: 'Focus timer', ja: '集中タイマー' } },
  { id: 'text-to-speech', title: { ko: '텍스트 음성 변환', en: 'Text to Speech', ja: 'テキスト読み上げ' }, emoji: '🔊', desc: { ko: 'TTS 음성 변환', en: 'TTS voice conversion', ja: 'TTS音声変換' } },
  { id: 'qr-scanner', title: { ko: 'QR 스캐너', en: 'QR Scanner', ja: 'QRスキャナー' }, emoji: '📷', desc: { ko: 'QR 코드 스캔', en: 'Scan QR codes', ja: 'QRコードスキャン' } },
  { id: 'password-strength', title: { ko: '비밀번호 강도', en: 'Password Strength', ja: 'パスワード強度' }, emoji: '🔒', desc: { ko: '비밀번호 보안 검사', en: 'Check password security', ja: 'パスワードセキュリティ検査' } },
  { id: 'morse-code', title: { ko: '모스 부호', en: 'Morse Code', ja: 'モールス信号' }, emoji: '📡', desc: { ko: '모스 부호 변환', en: 'Morse code converter', ja: 'モールス信号変換' } },
  { id: 'world-clock', title: { ko: '세계 시계', en: 'World Clock', ja: '世界時計' }, emoji: '🌍', desc: { ko: '전세계 시간 확인', en: 'Global time zones', ja: '世界の時刻確認' } },
  { id: 'typing-speed', title: { ko: '타이핑 속도', en: 'Typing Speed', ja: 'タイピング速度' }, emoji: '⌨️', desc: { ko: '타자 속도 테스트', en: 'Typing speed test', ja: 'タイピング速度テスト' } },
  { id: 'lorem-ipsum', title: { ko: 'Lorem Ipsum', en: 'Lorem Ipsum', ja: 'Lorem Ipsum' }, emoji: '📝', desc: { ko: '더미 텍스트 생성', en: 'Generate dummy text', ja: 'ダミーテキスト生成' } },
  { id: 'gradient-generator', title: { ko: '그라데이션', en: 'Gradient Generator', ja: 'グラデーション' }, emoji: '🎨', desc: { ko: 'CSS 그라디언트 생성', en: 'CSS gradient generator', ja: 'CSSグラデーション生成' } },
  { id: 'simple-calculator', title: { ko: '계산기', en: 'Calculator', ja: '電卓' }, emoji: '🔢', desc: { ko: '간단한 계산기', en: 'Simple calculator', ja: 'シンプルな計算機' } },
  { id: 'coin-age', title: { ko: '동전 나이', en: 'Coin Age', ja: 'コイン年齢' }, emoji: '🪙', desc: { ko: '동전 발행년도 계산', en: 'Calculate coin age', ja: 'コイン年齢計算' } },
  { id: 'font-preview', title: { ko: '폰트 미리보기', en: 'Font Preview', ja: 'フォントプレビュー' }, emoji: '🔤', desc: { ko: '다양한 폰트 미리보기', en: 'Preview various fonts', ja: '各種フォントプレビュー' } },
  { id: 'screen-color', title: { ko: '화면 색상 테스트', en: 'Screen Color Test', ja: '画面カラーテスト' }, emoji: '🖥️', desc: { ko: '모니터 불량 화소 테스트', en: 'Dead pixel test', ja: 'ドット抜けテスト' } },
  { id: 'countdown-event', title: { ko: '이벤트 카운트다운', en: 'Event Countdown', ja: 'イベントカウントダウン' }, emoji: '⏳', desc: { ko: '이벤트 날짜 카운트다운', en: 'Event date countdown', ja: 'イベント日カウントダウン' } },
  { id: 'random-quote', title: { ko: '랜덤 명언', en: 'Random Quote', ja: 'ランダム名言' }, emoji: '💬', desc: { ko: '명언 랜덤 생성', en: 'Random quote generator', ja: 'ランダム名言生成' } },
  { id: 'habit-tracker', title: { ko: '습관 트래커', en: 'Habit Tracker', ja: '習慣トラッカー' }, emoji: '✅', desc: { ko: '습관 관리 도구', en: 'Habit management tool', ja: '習慣管理ツール' } },
  { id: 'daily-checklist', title: { ko: '일일 체크리스트', en: 'Daily Checklist', ja: 'デイリーチェックリスト' }, emoji: '📋', desc: { ko: '하루 할 일 관리', en: 'Daily task management', ja: '毎日のタスク管理' } },
  { id: 'text-analyzer', title: { ko: '텍스트 분석기', en: 'Text Analyzer', ja: 'テキスト分析' }, emoji: '📊', desc: { ko: '텍스트 통계 분석', en: 'Text statistics analysis', ja: 'テキスト統計分析' } },
  { id: 'water-intake', title: { ko: '물 섭취 트래커', en: 'Water Intake Tracker', ja: '水分摂取トラッカー' }, emoji: '💧', desc: { ko: '하루 물 섭취량 관리', en: 'Track daily water intake', ja: '毎日の水分摂取量管理' } },
  { id: 'sleep-calculator', title: { ko: '수면 계산기', en: 'Sleep Calculator', ja: '睡眠計算機' }, emoji: '😴', desc: { ko: '최적 수면 시간 계산', en: 'Calculate optimal sleep time', ja: '最適な睡眠時間計算' } },
  { id: 'tip-calculator', title: { ko: '팁 계산기', en: 'Tip Calculator', ja: 'チップ計算機' }, emoji: '💵', desc: { ko: '팁 금액 계산', en: 'Calculate tip amount', ja: 'チップ金額計算' } },
  { id: 'split-bill', title: { ko: '더치페이 계산기', en: 'Split Bill', ja: '割り勘計算機' }, emoji: '🧮', desc: { ko: '더치페이 금액 계산', en: 'Split bill calculator', ja: '割り勘計算' } },
  { id: 'calorie-calculator', title: { ko: '칼로리 계산기', en: 'Calorie Calculator', ja: 'カロリー計算機' }, emoji: '🔥', desc: { ko: '일일 칼로리 계산', en: 'Daily calorie needs', ja: '1日のカロリー計算' } },
  { id: 'savings-goal', title: { ko: '저축 목표', en: 'Savings Goal', ja: '貯金目標' }, emoji: '💰', desc: { ko: '저축 목표 계산', en: 'Savings goal calculator', ja: '貯金目標計算' } },
  { id: 'loan-calculator', title: { ko: '대출 계산기', en: 'Loan Calculator', ja: 'ローン計算機' }, emoji: '🏦', desc: { ko: '대출 상환금 계산', en: 'Loan payment calculator', ja: 'ローン返済計算' } },
  { id: 'decision-maker', title: { ko: '결정 도우미', en: 'Decision Maker', ja: '決定ヘルパー' }, emoji: '🎯', desc: { ko: '랜덤 결정 도우미', en: 'Random decision helper', ja: 'ランダム決定ヘルパー' } },
  { id: 'priority-matrix', title: { ko: '우선순위 매트릭스', en: 'Priority Matrix', ja: '優先順位マトリックス' }, emoji: '📊', desc: { ko: '아이젠하워 매트릭스', en: 'Eisenhower matrix', ja: 'アイゼンハワーマトリックス' } },
  { id: 'gratitude-journal', title: { ko: '감사 일기', en: 'Gratitude Journal', ja: '感謝日記' }, emoji: '🙏', desc: { ko: '매일 감사 기록', en: 'Daily gratitude log', ja: '毎日感謝記録' } },
  { id: 'mood-tracker', title: { ko: '기분 트래커', en: 'Mood Tracker', ja: '気分トラッカー' }, emoji: '😊', desc: { ko: '매일 기분 기록', en: 'Daily mood log', ja: '毎日気分記録' } },
  { id: 'daily-affirmation', title: { ko: '오늘의 확언', en: 'Daily Affirmation', ja: '今日のアファメーション' }, emoji: '✨', desc: { ko: '긍정 확언 생성', en: 'Positive affirmations', ja: 'ポジティブアファメーション' } },
  { id: 'expense-tracker', title: { ko: '지출 기록기', en: 'Expense Tracker', ja: '支出トラッカー' }, emoji: '💸', desc: { ko: '월별 지출 관리', en: 'Monthly expense tracking', ja: '月別支出管理' } },
  { id: 'password-memory', title: { ko: '비밀번호 기억력', en: 'Password Memory', ja: 'パスワード記憶' }, emoji: '🔐', desc: { ko: '비밀번호 기억력 게임', en: 'Password memory game', ja: 'パスワード記憶ゲーム' } },
  { id: 'reading-list', title: { ko: '독서 목록', en: 'Reading List', ja: '読書リスト' }, emoji: '📚', desc: { ko: '읽은/읽을 책 관리', en: 'Manage reading list', ja: '読書リスト管理' } },
  { id: 'study-timer', title: { ko: '공부 타이머', en: 'Study Timer', ja: '勉強タイマー' }, emoji: '📖', desc: { ko: '공부 시간 측정', en: 'Track study time', ja: '勉強時間測定' } },
  { id: 'vocabulary-builder', title: { ko: '단어장', en: 'Vocabulary Builder', ja: '単語帳' }, emoji: '📝', desc: { ko: '단어 암기 학습', en: 'Learn vocabulary', ja: '単語暗記学習' } },
  { id: 'countdown-widget', title: { ko: '카운트다운 위젯', en: 'Countdown Widget', ja: 'カウントダウン' }, emoji: '⏰', desc: { ko: '이벤트 카운트다운', en: 'Event countdown', ja: 'イベントカウントダウン' } },
  { id: 'focus-music', title: { ko: '집중 음악', en: 'Focus Music', ja: '集中音楽' }, emoji: '🎵', desc: { ko: '집중력 향상 소리', en: 'Focus sounds', ja: '集中力向上サウンド' } },
  { id: 'recipe-saver', title: { ko: '레시피 저장', en: 'Recipe Saver', ja: 'レシピ保存' }, emoji: '🍳', desc: { ko: '요리 레시피 관리', en: 'Manage recipes', ja: 'レシピ管理' } },
  { id: 'daily-goals', title: { ko: '일일 목표', en: 'Daily Goals', ja: '毎日の目標' }, emoji: '🎯', desc: { ko: '하루 목표 관리', en: 'Daily goal tracker', ja: '毎日の目標管理' } },
  { id: 'budget-planner', title: { ko: '예산 계획', en: 'Budget Planner', ja: '予算計画' }, emoji: '💰', desc: { ko: '수입/지출 관리', en: 'Income/expense manager', ja: '収入と支出の管理' } },
  { id: 'quick-notes', title: { ko: '빠른 메모', en: 'Quick Notes', ja: 'クイックメモ' }, emoji: '📝', desc: { ko: '컬러 메모장', en: 'Colorful notes', ja: 'カラーメモ' } },
  { id: 'birthday-reminder', title: { ko: '생일 알림', en: 'Birthday Reminder', ja: '誕生日リマインダー' }, emoji: '🎂', desc: { ko: '생일 관리', en: 'Birthday tracker', ja: '誕生日管理' } },
  { id: 'wishlist', title: { ko: '위시리스트', en: 'Wishlist', ja: 'ウィッシュリスト' }, emoji: '🎁', desc: { ko: '갖고 싶은 것 관리', en: 'Manage wishlist', ja: 'ウィッシュリスト管理' } },
  { id: 'packing-list', title: { ko: '여행 짐싸기', en: 'Packing List', ja: 'パッキングリスト' }, emoji: '🧳', desc: { ko: '여행 준비물 체크', en: 'Travel packing checklist', ja: '旅行持ち物チェック' } },
  { id: 'bookmark-manager', title: { ko: '북마크 관리', en: 'Bookmark Manager', ja: 'ブックマーク管理' }, emoji: '🔖', desc: { ko: 'URL 북마크 관리', en: 'Manage URL bookmarks', ja: 'URLブックマーク管理' } },
  { id: 'plant-watering', title: { ko: '식물 물주기', en: 'Plant Watering', ja: '植物水やり' }, emoji: '🌱', desc: { ko: '식물 물주기 알림', en: 'Plant watering reminder', ja: '植物水やりリマインダー' } },
  { id: 'movie-watchlist', title: { ko: '영화 리스트', en: 'Movie Watchlist', ja: '映画リスト' }, emoji: '🎬', desc: { ko: '볼 영화 관리', en: 'Track movies to watch', ja: '視聴予定映画管理' } },
  { id: 'medication-reminder', title: { ko: '약 복용 알림', en: 'Medication Reminder', ja: '服薬リマインダー' }, emoji: '💊', desc: { ko: '약 복용 관리', en: 'Track medications', ja: '服薬管理' } },
  { id: 'meal-planner', title: { ko: '식단 계획', en: 'Meal Planner', ja: '食事プランナー' }, emoji: '🍽️', desc: { ko: '주간 식단 관리', en: 'Weekly meal planning', ja: '週間食事計画' } },
  { id: 'pet-care', title: { ko: '반려동물 관리', en: 'Pet Care', ja: 'ペットケア' }, emoji: '🐾', desc: { ko: '반려동물 돌봄', en: 'Pet care tracker', ja: 'ペット世話管理' } },
  { id: 'chore-chart', title: { ko: '집안일 차트', en: 'Chore Chart', ja: '家事チャート' }, emoji: '🧹', desc: { ko: '집안일 관리', en: 'Household chores', ja: '家事管理' } },
  { id: 'gift-ideas', title: { ko: '선물 아이디어', en: 'Gift Ideas', ja: 'ギフトアイデア' }, emoji: '🎁', desc: { ko: '선물 아이디어 관리', en: 'Track gift ideas', ja: 'ギフトアイデア管理' } },
  { id: 'clothes-organizer', title: { ko: '옷장 정리', en: 'Clothes Organizer', ja: 'クローゼット整理' }, emoji: '👗', desc: { ko: '옷장 관리', en: 'Organize closet', ja: 'クローゼット管理' } },
  { id: 'contact-manager', title: { ko: '연락처 관리', en: 'Contact Manager', ja: '連絡先管理' }, emoji: '📇', desc: { ko: '연락처 관리', en: 'Manage contacts', ja: '連絡先管理' } },
  { id: 'shopping-cart', title: { ko: '장바구니', en: 'Shopping Cart', ja: 'ショッピングカート' }, emoji: '🛒', desc: { ko: '장바구니 관리', en: 'Manage cart', ja: 'カート管理' } },
  { id: 'coupon-manager', title: { ko: '쿠폰 관리', en: 'Coupon Manager', ja: 'クーポン管理' }, emoji: '🎟️', desc: { ko: '쿠폰 코드 관리', en: 'Manage coupons', ja: 'クーポン管理' } },
  { id: 'event-planner', title: { ko: '이벤트 플래너', en: 'Event Planner', ja: 'イベントプランナー' }, emoji: '📅', desc: { ko: '이벤트 계획', en: 'Plan events', ja: 'イベント計画' } },
  { id: 'invoice-generator', title: { ko: '견적서 생성', en: 'Invoice Generator', ja: '請求書作成' }, emoji: '📄', desc: { ko: '견적서/청구서 생성', en: 'Create invoices', ja: '請求書作成' } },
  { id: 'rent-tracker', title: { ko: '월세 관리', en: 'Rent Tracker', ja: '家賃管理' }, emoji: '🏠', desc: { ko: '월세 납부 관리', en: 'Track rent payments', ja: '家賃支払い管理' } },
  { id: 'subscription-manager', title: { ko: '구독 관리', en: 'Subscription Manager', ja: 'サブスクリプション管理' }, emoji: '💳', desc: { ko: '구독 서비스 관리', en: 'Manage subscriptions', ja: 'サブスク管理' } },
  { id: 'warranty-tracker', title: { ko: '보증 관리', en: 'Warranty Tracker', ja: '保証管理' }, emoji: '🛡️', desc: { ko: '제품 보증 관리', en: 'Track warranties', ja: '保証期間管理' } },
  { id: 'fuel-log', title: { ko: '주유 기록', en: 'Fuel Log', ja: '給油記録' }, emoji: '⛽', desc: { ko: '주유 기록 관리', en: 'Track fuel consumption', ja: '給油記録管理' } },
  { id: 'parking-location', title: { ko: '주차 위치', en: 'Parking Location', ja: '駐車位置' }, emoji: '🚗', desc: { ko: '주차 위치 저장', en: 'Save parking spot', ja: '駐車位置保存' } },
  { id: 'wifi-password', title: { ko: 'WiFi 비밀번호', en: 'WiFi Password', ja: 'WiFiパスワード' }, emoji: '📶', desc: { ko: 'WiFi 비밀번호 저장', en: 'Save WiFi passwords', ja: 'WiFiパスワード保存' } },
  { id: 'size-converter', title: { ko: '사이즈 변환', en: 'Size Converter', ja: 'サイズ変換' }, emoji: '👕', desc: { ko: '옷/신발 사이즈 변환', en: 'Convert clothing sizes', ja: '服/靴サイズ変換' } },
  { id: 'currency-converter', title: { ko: '환율 계산기', en: 'Currency Converter', ja: '為替計算機' }, emoji: '💱', desc: { ko: '환율 변환', en: 'Convert currencies', ja: '為替変換' } },
  { id: 'price-compare', title: { ko: '단가 비교', en: 'Price Compare', ja: '単価比較' }, emoji: '⚖️', desc: { ko: '단가 비교 계산', en: 'Compare unit prices', ja: '単価比較計算' } },
  { id: 'business-card', title: { ko: '디지털 명함', en: 'Digital Business Card', ja: 'デジタル名刺' }, emoji: '💼', desc: { ko: '디지털 명함 만들기', en: 'Create digital business card', ja: 'デジタル名刺作成' } },
  { id: 'flashcard', title: { ko: '플래시카드', en: 'Flashcards', ja: 'フラッシュカード' }, emoji: '📚', desc: { ko: '플래시카드 학습', en: 'Study with flashcards', ja: 'フラッシュカード学習' } },
  { id: 'eye-rest', title: { ko: '눈 휴식', en: 'Eye Rest Timer', ja: '目の休憩タイマー' }, emoji: '👁️', desc: { ko: '20-20-20 눈 휴식', en: '20-20-20 eye rest rule', ja: '20-20-20目の休憩' } },
  { id: 'daily-journal', title: { ko: '오늘의 일기', en: 'Daily Journal', ja: '今日の日記' }, emoji: '📔', desc: { ko: '매일 일기 쓰기', en: 'Write daily journal', ja: '毎日日記を書く' } },
  { id: 'wish-counter', title: { ko: '소원 카운터', en: 'Wish Counter', ja: '願いカウンター' }, emoji: '🌟', desc: { ko: '소원 빌기 카운터', en: 'Track your wishes', ja: '願いを数える' } },
  { id: 'grocery-list', title: { ko: '장보기 목록', en: 'Grocery List', ja: '買い物リスト' }, emoji: '🛒', desc: { ko: '장보기 체크리스트', en: 'Grocery shopping list', ja: '買い物チェックリスト' } },
  { id: 'personal-timer', title: { ko: '나만의 타이머', en: 'Personal Timer', ja: 'マイタイマー' }, emoji: '⏱️', desc: { ko: '커스텀 타이머', en: 'Custom countdown timer', ja: 'カスタムタイマー' } },
  { id: 'speed-test', title: { ko: '인터넷 속도', en: 'Speed Test', ja: '速度テスト' }, emoji: '🚀', desc: { ko: '인터넷 속도 측정', en: 'Internet speed test', ja: 'ネット速度測定' } },
  { id: 'lucky-number', title: { ko: '행운의 숫자', en: 'Lucky Number', ja: 'ラッキーナンバー' }, emoji: '🍀', desc: { ko: '행운의 숫자 생성', en: 'Generate lucky numbers', ja: 'ラッキーナンバー生成' } },
  { id: 'daily-quote', title: { ko: '오늘의 명언', en: 'Daily Quote', ja: '今日の名言' }, emoji: '💬', desc: { ko: '명언 모음', en: 'Inspirational quotes', ja: '名言・格言集' } },
  { id: 'typing-practice', title: { ko: '타자 연습', en: 'Typing Practice', ja: 'タイピング練習' }, emoji: '⌨️', desc: { ko: '타자 연습', en: 'Practice typing', ja: 'タイピング練習' } },
  { id: 'photo-filter', title: { ko: '사진 필터', en: 'Photo Filter', ja: '写真フィルター' }, emoji: '📸', desc: { ko: '사진 필터 편집', en: 'Photo filter editor', ja: '写真フィルター編集' } },
  { id: 'tic-tac-toe', title: { ko: '틱택토', en: 'Tic Tac Toe', ja: '三目並べ' }, emoji: '⭕', desc: { ko: '틱택토 게임', en: 'Tic tac toe game', ja: '三目並べゲーム' } },
  { id: 'score-board', title: { ko: '점수판', en: 'Score Board', ja: 'スコアボード' }, emoji: '🏆', desc: { ko: '경기 점수 기록', en: 'Track game scores', ja: '試合スコア記録' } },
  { id: 'memory-match', title: { ko: '기억력 게임', en: 'Memory Match', ja: '神経衰弱' }, emoji: '🧠', desc: { ko: '카드 짝 맞추기', en: 'Card matching game', ja: 'カードマッチングゲーム' } },
  { id: 'word-scramble', title: { ko: '단어 맞추기', en: 'Word Scramble', ja: '単語パズル' }, emoji: '🔤', desc: { ko: '단어 퍼즐 게임', en: 'Word puzzle game', ja: '単語パズルゲーム' } },
  { id: 'click-counter', title: { ko: '클릭 카운터', en: 'Click Counter', ja: 'クリックカウンター' }, emoji: '👆', desc: { ko: '클릭 수 세기', en: 'Count your clicks', ja: 'クリック数カウント' } },
  { id: 'drawing-pad', title: { ko: '그림판', en: 'Drawing Pad', ja: 'お絵かき帳' }, emoji: '🎨', desc: { ko: '간단한 그림판', en: 'Simple drawing pad', ja: 'シンプルお絵かき' } },
  { id: 'rock-paper-scissors', title: { ko: '가위바위보', en: 'Rock Paper Scissors', ja: 'じゃんけん' }, emoji: '✊', desc: { ko: '가위바위보 게임', en: 'Rock paper scissors game', ja: 'じゃんけんゲーム' } },
  { id: 'reaction-test', title: { ko: '반응속도', en: 'Reaction Test', ja: '反応速度' }, emoji: '⚡', desc: { ko: '반응속도 테스트', en: 'Reaction time test', ja: '反応速度テスト' } },
  { id: 'number-guessing', title: { ko: '숫자 맞추기', en: 'Number Guessing', ja: '数字当て' }, emoji: '🔢', desc: { ko: '숫자 맞추기 게임', en: 'Guess the number', ja: '数字当てゲーム' } },
  { id: 'hangman', title: { ko: '행맨', en: 'Hangman', ja: 'ハングマン' }, emoji: '🎯', desc: { ko: '행맨 단어 게임', en: 'Word guessing game', ja: '単語推測ゲーム' } },
  { id: 'simon-says', title: { ko: '사이먼 게임', en: 'Simon Game', ja: 'サイモンゲーム' }, emoji: '🎮', desc: { ko: '기억력 패턴 게임', en: 'Memory pattern game', ja: '記憶パターンゲーム' } },
  { id: 'color-picker-game', title: { ko: '컬러 맞추기', en: 'Color Match', ja: 'カラーマッチ' }, emoji: '🌈', desc: { ko: '색상 맞추기 게임', en: 'Color matching game', ja: '色当てゲーム' } },
  { id: 'quiz-game', title: { ko: '퀴즈 게임', en: 'Quiz Game', ja: 'クイズゲーム' }, emoji: '🧠', desc: { ko: '상식 퀴즈', en: 'Trivia quiz game', ja: '雑学クイズ' } },
  { id: 'spin-wheel', title: { ko: '돌림판', en: 'Spin Wheel', ja: 'ルーレット' }, emoji: '🎡', desc: { ko: '랜덤 돌림판', en: 'Random spin wheel', ja: 'ランダムルーレット' } },
  { id: 'snake-game', title: { ko: '뱀 게임', en: 'Snake Game', ja: 'スネークゲーム' }, emoji: '🐍', desc: { ko: '클래식 뱀 게임', en: 'Classic snake game', ja: 'クラシックスネークゲーム' } },
  { id: '2048-game', title: { ko: '2048 게임', en: '2048 Game', ja: '2048ゲーム' }, emoji: '🔢', desc: { ko: '숫자 퍼즐 게임', en: 'Number puzzle game', ja: '数字パズルゲーム' } },
  { id: 'tetris-game', title: { ko: '테트리스', en: 'Tetris', ja: 'テトリス' }, emoji: '🧱', desc: { ko: '블록 쌓기 게임', en: 'Block stacking game', ja: 'ブロック積みゲーム' } },
  { id: 'breakout-game', title: { ko: '벽돌깨기', en: 'Breakout', ja: 'ブロック崩し' }, emoji: '🧱', desc: { ko: '벽돌 깨기 게임', en: 'Brick breaking game', ja: 'ブロック崩しゲーム' } },
  { id: 'flappy-bird', title: { ko: '플래피 버드', en: 'Flappy Bird', ja: 'フラッピーバード' }, emoji: '🐦', desc: { ko: '플래피 버드 게임', en: 'Flappy bird game', ja: 'フラッピーバードゲーム' } },
  { id: 'minesweeper', title: { ko: '지뢰찾기', en: 'Minesweeper', ja: 'マインスイーパー' }, emoji: '💣', desc: { ko: '지뢰찾기 게임', en: 'Minesweeper game', ja: 'マインスイーパーゲーム' } },
  { id: 'pong-game', title: { ko: '퐁 게임', en: 'Pong Game', ja: 'ポンゲーム' }, emoji: '🏓', desc: { ko: '퐁 게임', en: 'Classic pong game', ja: 'ポンゲーム' } },
  { id: 'wordle-game', title: { ko: '워들 게임', en: 'Wordle Game', ja: 'ワードルゲーム' }, emoji: '📝', desc: { ko: '단어 맞추기', en: 'Word guessing game', ja: '単語当てゲーム' } },
  { id: 'connect-four', title: { ko: '사목 게임', en: 'Connect Four', ja: '四目並べ' }, emoji: '🔴', desc: { ko: '사목 게임', en: 'Connect four game', ja: '四目並べゲーム' } },
  { id: 'sudoku', title: { ko: '스도쿠', en: 'Sudoku', ja: '数独' }, emoji: '🔢', desc: { ko: '스도쿠 퍼즐', en: 'Sudoku puzzle', ja: '数独パズルゲーム' } },
  { id: 'slot-machine', title: { ko: '슬롯머신', en: 'Slot Machine', ja: 'スロットマシン' }, emoji: '🎰', desc: { ko: '슬롯머신 게임', en: 'Slot machine game', ja: 'スロットマシンゲーム' } },
  { id: 'magic-8-ball', title: { ko: '마법의 8볼', en: 'Magic 8 Ball', ja: 'マジック8ボール' }, emoji: '🎱', desc: { ko: '마법의 8볼', en: 'Magic 8 ball', ja: 'マジック8ボール' } },
  { id: 'spinning-wheel', title: { ko: '룰렛 돌리기', en: 'Spinning Wheel', ja: 'ルーレット' }, emoji: '🎡', desc: { ko: '룰렛 돌리기', en: 'Spin the wheel', ja: 'ルーレットを回す' } },
  { id: 'fortune-cookie', title: { ko: '포춘쿠키', en: 'Fortune Cookie', ja: 'フォーチュンクッキー' }, emoji: '🥠', desc: { ko: '포춘쿠키 운세', en: 'Fortune cookie', ja: 'フォーチュンクッキー' } },
  { id: 'number-picker', title: { ko: '숫자 뽑기', en: 'Number Picker', ja: '数字ピッカー' }, emoji: '🔢', desc: { ko: '랜덤 숫자 뽑기', en: 'Random number picker', ja: 'ランダム数字選択' } },
  { id: 'scratch-card', title: { ko: '스크래치 카드', en: 'Scratch Card', ja: 'スクラッチカード' }, emoji: '🎫', desc: { ko: '스크래치 카드', en: 'Scratch card game', ja: 'スクラッチカード' } },
  { id: 'bingo-caller', title: { ko: '빙고 콜러', en: 'Bingo Caller', ja: 'ビンゴコーラー' }, emoji: '🎯', desc: { ko: '빙고 번호 뽑기', en: 'Bingo number caller', ja: 'ビンゴ番号コール' } },
  { id: 'tarot-card', title: { ko: '타로 카드', en: 'Tarot Card', ja: 'タロットカード' }, emoji: '🔮', desc: { ko: '타로 카드 리딩', en: 'Tarot card reading', ja: 'タロットカードリーディング' } },
  { id: 'horoscope', title: { ko: '오늘의 운세', en: 'Daily Horoscope', ja: '今日の運勢' }, emoji: '⭐', desc: { ko: '별자리 운세', en: 'Zodiac horoscope', ja: '星座占い' } },
  { id: 'card-draw', title: { ko: '카드 뽑기', en: 'Card Draw', ja: 'カードドロー' }, emoji: '🃏', desc: { ko: '카드 뽑기', en: 'Draw playing cards', ja: 'トランプを引く' } },
  { id: 'lucky-draw', title: { ko: '행운 뽑기', en: 'Lucky Draw', ja: 'ラッキードロー' }, emoji: '🎁', desc: { ko: '행운 상자 뽑기', en: 'Lucky box draw', ja: 'ラッキーボックス' } },
  { id: 'love-calculator', title: { ko: '사랑 계산기', en: 'Love Calculator', ja: '相性診断' }, emoji: '💕', desc: { ko: '사랑 궁합 테스트', en: 'Love compatibility test', ja: '恋愛相性テスト' } },
  { id: 'trivia-quiz', title: { ko: '상식 퀴즈', en: 'Trivia Quiz', ja: '雑学クイズ' }, emoji: '🧠', desc: { ko: '상식 퀴즈 게임', en: 'Trivia quiz game', ja: '雑学クイズゲーム' } },
  { id: 'emoji-puzzle', title: { ko: '이모지 퍼즐', en: 'Emoji Puzzle', ja: '絵文字パズル' }, emoji: '🧩', desc: { ko: '이모지 맞추기', en: 'Guess the emoji', ja: '絵文字クイズ' } },
  { id: 'truth-or-dare', title: { ko: '진실 혹은 도전', en: 'Truth or Dare', ja: '真実か挑戦' }, emoji: '🎭', desc: { ko: '진실 혹은 도전 게임', en: 'Truth or dare game', ja: '真実か挑戦ゲーム' } },
  { id: 'would-you-rather', title: { ko: '이거 아니면 저거', en: 'Would You Rather', ja: 'どっちを選ぶ' }, emoji: '🤔', desc: { ko: '선택 게임', en: 'Choice game', ja: '選択ゲーム' } },
  { id: 'finger-roulette', title: { ko: '손가락 룰렛', en: 'Finger Roulette', ja: '指ルーレット' }, emoji: '👆', desc: { ko: '손가락 룰렛 게임', en: 'Finger roulette game', ja: '指ルーレットゲーム' } },
  { id: 'bottle-spin', title: { ko: '병 돌리기', en: 'Spin the Bottle', ja: 'ボトル回し' }, emoji: '🍾', desc: { ko: '병 돌리기 게임', en: 'Spin the bottle game', ja: 'ボトル回しゲーム' } },
  { id: 'personality-test', title: { ko: '성격 테스트', en: 'Personality Test', ja: '性格診断' }, emoji: '🧠', desc: { ko: 'MBTI 성격 유형 테스트', en: 'MBTI personality type test', ja: 'MBTI性格タイプ診断' } },
  { id: 'color-blind-test', title: { ko: '색맹 테스트', en: 'Color Blind Test', ja: '色覚テスト' }, emoji: '👁️', desc: { ko: '색맹/색약 테스트', en: 'Color blindness test', ja: '色覚異常テスト' } },
  { id: 'never-have-i-ever', title: { ko: '나는 ~한 적 없다', en: 'Never Have I Ever', ja: '私は〜したことがない' }, emoji: '🙈', desc: { ko: '파티 게임', en: 'Party game', ja: 'パーティーゲーム' } },
  { id: 'charades', title: { ko: '제스처 게임', en: 'Charades', ja: 'ジェスチャーゲーム' }, emoji: '🎭', desc: { ko: '몸으로 말해요', en: 'Act it out game', ja: 'ジェスチャーで伝えよう' } },
  { id: 'hot-seat', title: { ko: '핫시트', en: 'Hot Seat', ja: 'ホットシート' }, emoji: '🔥', desc: { ko: '뜨거운 질문 게임', en: 'Burning questions game', ja: '熱い質問ゲーム' } },
  { id: 'word-association', title: { ko: '연상 게임', en: 'Word Association', ja: '連想ゲーム' }, emoji: '🔗', desc: { ko: '단어 연상 게임', en: 'Word association game', ja: '連想ゲーム' } },
  { id: 'draw-something', title: { ko: '그림 맞추기', en: 'Draw Something', ja: 'お絵かきゲーム' }, emoji: '🎨', desc: { ko: '그림 맞추기 게임', en: 'Drawing guessing game', ja: 'お絵かき当てゲーム' } },
  { id: 'countdown-timer', title: { ko: '카운트다운 타이머', en: 'Countdown Timer', ja: 'カウントダウンタイマー' }, emoji: '⏱️', desc: { ko: '카운트다운 타이머', en: 'Countdown timer', ja: 'カウントダウンタイマー' } },
  { id: 'two-truths-one-lie', title: { ko: '두 개의 진실 하나의 거짓', en: 'Two Truths One Lie', ja: '2つの真実と1つの嘘' }, emoji: '✌️', desc: { ko: '진실과 거짓 게임', en: 'Truth and lie game', ja: '真実と嘘ゲーム' } },
  { id: 'category-game', title: { ko: '카테고리 게임', en: 'Category Game', ja: 'カテゴリーゲーム' }, emoji: '📋', desc: { ko: '카테고리 단어 게임', en: 'Category word game', ja: 'カテゴリーワードゲーム' } },
  { id: 'mafia-role', title: { ko: '마피아 역할 배정', en: 'Mafia Role Assigner', ja: 'マフィア役割配布' }, emoji: '🎭', desc: { ko: '마피아 게임 역할 배정', en: 'Mafia game role assignment', ja: 'マフィアゲーム役割配布' } },
  { id: 'team-picker', title: { ko: '팀 나누기', en: 'Team Picker', ja: 'チーム分け' }, emoji: '👥', desc: { ko: '랜덤 팀 나누기', en: 'Random team divider', ja: 'ランダムチーム分け' } },
  { id: 'heads-up', title: { ko: '헤드업 게임', en: 'Heads Up Game', ja: 'ヘッズアップゲーム' }, emoji: '🙆', desc: { ko: '이마 위 단어 맞추기', en: 'Forehead word guessing', ja: 'おでこ単語当てゲーム' } },
  { id: 'word-bomb', title: { ko: '단어 폭탄', en: 'Word Bomb', ja: 'ワードボム' }, emoji: '💣', desc: { ko: '폭탄 터지기 전 단어 말하기', en: 'Say word before bomb explodes', ja: '爆発前に言葉を言え' } },
  { id: 'balance-game', title: { ko: '밸런스 게임', en: 'Balance Game', ja: 'バランスゲーム' }, emoji: '⚖️', desc: { ko: '어려운 선택 게임', en: 'Difficult choice game', ja: '難しい選択ゲーム' } },
  { id: 'speed-quiz', title: { ko: '스피드 퀴즈', en: 'Speed Quiz', ja: 'スピードクイズ' }, emoji: '⚡', desc: { ko: '힌트 보고 빠르게 맞추기', en: 'Guess quickly from hints', ja: 'ヒントから素早く当てよう' } },
  { id: 'song-guess', title: { ko: '노래 맞추기', en: 'Song Guess', ja: '曲当てゲーム' }, emoji: '🎵', desc: { ko: '가사 보고 노래 맞추기', en: 'Guess songs from lyrics', ja: '歌詞から曲を当てよう' } },
  { id: 'whisper-challenge', title: { ko: '속삭임 챌린지', en: 'Whisper Challenge', ja: 'ささやきチャレンジ' }, emoji: '🤫', desc: { ko: '헤드폰 끼고 입모양 읽기', en: 'Lip reading with headphones', ja: 'ヘッドホンで口読み' } }
];

module.exports = { webTools: webTools, consumerTools: consumerTools };
